### ISSUE TITLE
YAY! POD3 checksum algorithms are fully ready!

### ISSUE THREAD

**Issue by PavelSharp** [jopadan/libpodfmt#4]
Hello. I did my own research work on the algorithm for checksums of POD3 files that are used in Br1 and Br2. And thus came to the following conclusion:

1. POD3 prefer the standard [CRC-32/MPEG-2](https://crccalc.com/?crc=123456789&method=CRC-32/MPEG-2&datatype=0&outtype=0)
2. `pod3_entry_s::checksum` this is just a checksum for the entity (obviously)
3. And now the main thing, `pod_header_pod3_s::checksum` - this is nothing more than the checksum of the header, excluding the first 8 bytes. Therefore, this is a checksum taken from offset 8, and the length is 280 bytes.
As we can see, the POD3 does not store the checksum of the entire file, instead it stores the checksum of each section(header + each entity).

**Comment by jopadan** [comment]
Thank you for submitting the header checksum offsets. The algorithm seems to be the same as the other POD versions.
See also updated [jtrfp#3](https://github.com/jtrfp/jtrfp/issues/3) and [POD Format Reference](https://github.com/jtrfp/jtrfp/wiki/POD-Format-Reference)

**Comment by PavelSharp** [comment]
I am happy to receive an answer. Would you like to update the table on the [main page](https://github.com/jopadan/libtermpod)?
Since the "no" in the cells forms an incorrect opinion, according to which the checksum algorithms stay unknown. However, using the original game archives, we can verify that it is CRC-32/MPEG-2(or CRC-CCITT32 if it same) for POD3.

**Comment by jopadan** [comment]
I've updated the README.md and initiated a complete rewrite/switch to C++

**Comment by PavelSharp** [comment]
@jopadan My thanks for all the work you've done. A few other trivia:

- In the near future, I plan to publish source code of my own utility that supports conversions of Br2 files like pod, tex, smb, skb, bfm. I will do this as soon as I finish the ani format. Feel free to share your thoughts on this.
- I have a little more information about POD formats that I could contribute to the Wiki. Alternatively, I could create a relevant issue

**Comment by jopadan** [comment]
You are welcome feel free to contribute your additions to the Wiki.

**Comment by PavelSharp** [comment]
@jopadan I would love to do this, but unfortunately, I currently do not have permission to edit this [Wiki](https://github.com/jopadan/libtermpod/wiki/).

**Comment by jopadan** [comment]
@PavelSharp I have send you an invitation to collaborate you should be able to edit it then.
